= Ansible Best Practices

== Version Control

== YAML

=== Use Block Quotes

```
- name: Run Installer Script
  command: >-
    installer.sh
    --config=example/config/path
    --domain=app23.example.com
    --enable-advanced-features
    --admin-password={{ admin_password | quote }}
  args:
    creates: /etc/example/install.log
```

```
- name: Deployment for MyApp
  k8s:
    state: present
    definition: "{{ myapp_deployment }}"
  when: >-
    myapp_install_k8s|bool or
    myapp_install_openshift|bool
```

== Idempotence

Levels of code quality:

* Ansible code works once, cannot re-run
* Check if code has run, avoids reconfiguring
* Checks can reset, reconfigure
* Reconfiguration properly indicates changes

== Inventory

=== Use YAML

=== Use `group_vars`

=== Avoid `host_vars`

Hosts should normally be grouped to specify the purpose assigned to each host.
Even if there is only one host in a group, use of groups still provides clarity.

=== Group Naming

== Playbook

=== Name your plays

=== Avoid `group_vars` and `host_vars`?

Using `group_vars` and `host_vars` in a playbook requires strict rules of ansible group naming which are best avoided.
It is better practice to have variables for host and group names when a playbook needs different handling depending on the host or host group.
If sets of variables need to be set based on group, try using `include_vars` instead using a check on the hosts groups (`group_names` special variable).

--------------------------------------------------------------------------------
- name: Include Database Host Vars
  when: myplaybook_database_group_name in group_names
  include_vars:
    dir: vars/database/
--------------------------------------------------------------------------------

== Roles

* Use Roles

== Tasks

=== Name your tasks

=== User `verbosity` with `debug` tasks

=== Error Handling

Do not `ignore_errors`.
Using `ignore_errors` still reports an error and is often confusing.

Use `failed_when` instead.
Using `failed_when` allows you to give your own error conditions.

https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html

=== Fail early with `assert` and `fail`

--------------------------------------------------------------------------------
- name: Check for valid url
  fail:
    msg: Invalid url: {{ myapp_url }}
  when: >-
    not myapp_url.startswith('https://') or
    not myapp_url is search('/myapp/')
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
- name: Assert valid url
  assert:
  - myapp_url.startswith('https://') or
  - myapp_url is search('/myapp/')
--------------------------------------------------------------------------------

=== `command` module

* Use sparingly
* Use `quote` filter with variables
* Calling shell scripts from command?
** Template shell script and copy to host
* Don't call `ansible` or `ansible-playbook` from `command`
* Use args:
** `chdir` Set working directory for command
** `creates` Only run if file does not exist
** `removes` Only run if file exists
** `warn` Use to disable warnings

=== `shell` module

* Only use `shell` if you cannot use `command`

== Variables

=== Avoid `set_fact` unless it is a fact about the host

Set vars on `include_tasks` or `include_role` instead.

=== Include all variables for configuration in `defaults/main.yml`

=== Process variables in `vars/main.yml`

=== Prefix Variable Names

--------------------------------------------------------------------------------
myapp_version: latest
myapp_openshift_image: quay.io/myorg/myapp:{{ myapp_version }}
myapp_openshift_dev_nampsace: mapp-dev
--------------------------------------------------------------------------------

== Testing

== Lookup Plugins

== Filters

=== Use `default` filter

=== Pass all boolean values through `bool`

=== Use `quote` filter on commands

=== Use `to_json` filter in generated YAML

== Custom Modules

== Templating with Jinja2

=== Template indentation
